title:             Tardif Lab
email:             christine.tardif@mcgill.ca
tagline:           " A VIEW OF BRAIN MICROSTRUCTURE USING MRI"
description:       "Magnetic resonance imaging lab of brain tissue microstructure, Montreal Neurological Institute, McGill University."

baseurl:           /labtestwebsite2
url:               https://tardiflab.github.io

twitter:           "tardiftweets"
github:            "tardiflab"
researchgate:      "Christine_Tardif"
google-scholar:     "citations?user=6EoHjugAAAAJ&hl=en&oi=ao"

pages:
- {title: 'About', url: 'pages/about.html'}
- {title: 'Publications', url: 'pages/publications.html'}
- {title: 'Join', url: 'pages/join.html'}

# Build settings
markdown: kramdown
