title:             Tardif Lab
email:             christine.tardif@mcgill.ca
tagline: "a view of brain microstructure in vivo using MRI"
description:  "Magnetic resonance imaging lab of brain tissue microstructure, Montreal Neurological Institute, McGill University."

baseurl:           /labwebsite
url:               https://tardiflab.github.io

twitter:           "tardiftweets"
github:            "tardiflab"
researchgate:      "Christine_Tardif"
google-scholar:     "citations?user=6EoHjugAAAAJ&hl=en&oi=ao"
#linkedin:          "lenpaul"

pages:
- {title: 'About', url: 'pages/about.html'}

# Build settings
markdown: kramdown
