title:             Paul Le
email:             l.nguyen.paul@gmail.com
description:
baseurl:           /website
url:               https://tardiflab.github.io
twitter:           "paululele"
github:            "lenpaul"
codepen:           "lenpaul"
linkedin:          "lenpaul"
instagram:         "paululele"

# Build settings
markdown: kramdown
